In [23]:
import gc
import pandas as pd
import numpy as np 
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

from sklearn import metrics

from sklearn.model_selection import cross_validate, GridSearchCV
from sklearn.model_selection import train_test_split
# 相关全局设置
pd.set_option('display.max_columns', None)
sns.set()

In [24]:
data_train = pd.read_csv('modeling_df(1).csv', encoding='ISO-8859-1')
#data_testA = pd.read_csv('modeling_df(1).csv')

In [25]:
data_train

,review_id,user_id,business_id,comment_star,date,name,city,average_stars,review_count,BusinessAcceptsCreditCards,BikeParking,RestaurantsTakeOut,RestaurantsReservations,RestaurantsTableService,GoodForKids,WheelchairAccessible,RestaurantsDelivery,HasTV,Alcohol,DogsAllowed,RestaurantsGoodForGroups,WiFi,garage,street,lot,valet,dessert,latenight,lunch,dinner,brunch,breakfast,Total_hour,acceptable_noise,general_category,hipster_trendy,upscale_classy,divey_env,intimate_env,casual_env
0,cSsTxwkhjUTOUkLt7Y4LAA,_QrXKSZm2D6iPQqwChxsiw,MiMRlsXOpHJMSTDAuw8s1w,4,2020-02-07 00:29:55,Suâs Bowl,Isla Vista,3.5,18,True,True,True,False,False,NaN,NaN,True,True,False,False,NaN,True,True,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,44.0,NaN,Asian Fusion,NaN,NaN,NaN,NaN,NaN
1,vz9y6qxlZkttwprvVEbWmw,2PeqtdiehYm82TXymQUGow,MiMRlsXOpHJMSTDAuw8s1w,4,2020-07-23 03:31:41,Suâs Bowl,Isla Vista,3.5,18,True,True,True,False,False,NaN,NaN,True,True,False,False,NaN,True,True,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,44.0,NaN,Asian Fusion,NaN,NaN,NaN,NaN,NaN
2,A27fyLXY_wsoEi61uZR8qQ,En60uoM-AoTtQ9-nZco92A,MiMRlsXOpHJMSTDAuw8s1w,3,2020-03-23 01:03:20,Suâs Bowl,Isla Vista,3.5,18,True,True,True,False,False,NaN,NaN,True,True,False,False,NaN,True,True,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,44.0,NaN,Asian Fusion,NaN,NaN,NaN,NaN,NaN
3,_FhgxOElUpqgVu6NYQ_bkg,LcBZt_bpU5CqwtDJwB3OCg,MiMRlsXOpHJMSTDAuw8s1w,4,2019-12-09 01:15:53,Suâs Bowl,Isla Vista,3.5,18,True,True,True,False,False,NaN,NaN,True,True,False,False,NaN,True,True,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,44.0,NaN,Asian Fusion,NaN,NaN,NaN,NaN,NaN
4,9yKOHgmubnxyIzoWRKad7w,FxdCb7Dl8c2hYn2t_7qRBA,MiMRlsXOpHJMSTDAuw8s1w,5,2020-12-12 03:17:49,Suâs Bowl,Isla Vista,3.5,18,True,True,True,False,False,NaN,NaN,True,True,False,False,NaN,True,True,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,44.0,NaN,Asian Fusion,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14819,DtTPlU8KX5q_AJxYh_ctuA,RLW98dloIcfl57JPK5rMXQ,2xxkaRy7rP5EUyjFt2J5kA,5,2020-05-01 00:00:29,Nikka Ramen,Goleta,4.5,562,True,True,True,False,True,True,True,True,True,True,False,True,True,False,False,True,False,False,False,True,True,NaN,False,24.0,True,Japanese,True,False,False,False,True
14820,LrkKYQE4GFbrLljB1e-1uQ,7CSdKgXpErpxNDlcxRNmyw,2xxkaRy7rP5EUyjFt2J5kA,5,2021-12-31 02:09:13,Nikka Ramen,Goleta,4.5,562,True,True,True,False,True,True,True,True,True,True,False,True,True,False,False,True,False,False,False,True,True,NaN,False,24.0,True,Japanese,True,False,False,False,True
14821,ANLkn3qlUFauQx2QvYCpOA,GHtcfd7DYF_awESn6jCBtQ,2xxkaRy7rP5EUyjFt2J5kA,5,2020-10-11 22:16:48,Nikka Ramen,Goleta,4.5,562,True,True,True,False,True,True,True,True,True,True,False,True,True,False,False,True,False,False,False,True,True,NaN,False,24.0,True,Japanese,True,False,False,False,True
14822,faZzKA1okAUGVDh-AC4X4w,n6fiQSlPZiRojE55MS77yg,2xxkaRy7rP5EUyjFt2J5kA,3,2021-12-13 03:19:20,Nikka Ramen,Goleta,4.5,562,True,True,True,False,True,True,True,True,True,True,False,True,True,False,False,True,False,False,False,True,True,NaN,False,24.0,True,Japanese,True,False,False,False,True
14823,Thf0D-SqPeXcn3faH7rM3Q,y783d3C4Yjm_cGqHvPQnmA,2xxkaRy7rP5EUyjFt2J5kA,4,2017-03-12 06:45:25,Nikka Ramen,Goleta,4.5,562,True,True,True,False,True,True,True,True,True,True,False,True,True,False,False,True,False,False,False,True,True,NaN,False,24.0,True,Japanese,True,False,False,False,True

In [26]:
data_train.head().append(data_train.tail())
data_train.describe()
data_train.info()

C:\Users\86188\AppData\Local\Temp\ipykernel_31040\3004579156.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data_train.head().append(data_train.tail())

,review_id,user_id,business_id,comment_star,date,name,city,average_stars,review_count,BusinessAcceptsCreditCards,BikeParking,RestaurantsTakeOut,RestaurantsReservations,RestaurantsTableService,GoodForKids,WheelchairAccessible,RestaurantsDelivery,HasTV,Alcohol,DogsAllowed,RestaurantsGoodForGroups,WiFi,garage,street,lot,valet,dessert,latenight,lunch,dinner,brunch,breakfast,Total_hour,acceptable_noise,general_category,hipster_trendy,upscale_classy,divey_env,intimate_env,casual_env
0,cSsTxwkhjUTOUkLt7Y4LAA,_QrXKSZm2D6iPQqwChxsiw,MiMRlsXOpHJMSTDAuw8s1w,4,2020-02-07 00:29:55,Suâs Bowl,Isla Vista,3.5,18,True,True,True,False,False,NaN,NaN,True,True,False,False,NaN,True,True,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,44.0,NaN,Asian Fusion,NaN,NaN,NaN,NaN,NaN
1,vz9y6qxlZkttwprvVEbWmw,2PeqtdiehYm82TXymQUGow,MiMRlsXOpHJMSTDAuw8s1w,4,2020-07-23 03:31:41,Suâs Bowl,Isla Vista,3.5,18,True,True,True,False,False,NaN,NaN,True,True,False,False,NaN,True,True,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,44.0,NaN,Asian Fusion,NaN,NaN,NaN,NaN,NaN
2,A27fyLXY_wsoEi61uZR8qQ,En60uoM-AoTtQ9-nZco92A,MiMRlsXOpHJMSTDAuw8s1w,3,2020-03-23 01:03:20,Suâs Bowl,Isla Vista,3.5,18,True,True,True,False,False,NaN,NaN,True,True,False,False,NaN,True,True,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,44.0,NaN,Asian Fusion,NaN,NaN,NaN,NaN,NaN
3,_FhgxOElUpqgVu6NYQ_bkg,LcBZt_bpU5CqwtDJwB3OCg,MiMRlsXOpHJMSTDAuw8s1w,4,2019-12-09 01:15:53,Suâs Bowl,Isla Vista,3.5,18,True,True,True,False,False,NaN,NaN,True,True,False,False,NaN,True,True,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,44.0,NaN,Asian Fusion,NaN,NaN,NaN,NaN,NaN
4,9yKOHgmubnxyIzoWRKad7w,FxdCb7Dl8c2hYn2t_7qRBA,MiMRlsXOpHJMSTDAuw8s1w,5,2020-12-12 03:17:49,Suâs Bowl,Isla Vista,3.5,18,True,True,True,False,False,NaN,NaN,True,True,False,False,NaN,True,True,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,44.0,NaN,Asian Fusion,NaN,NaN,NaN,NaN,NaN
14819,DtTPlU8KX5q_AJxYh_ctuA,RLW98dloIcfl57JPK5rMXQ,2xxkaRy7rP5EUyjFt2J5kA,5,2020-05-01 00:00:29,Nikka Ramen,Goleta,4.5,562,True,True,True,False,True,True,True,True,True,True,False,True,True,False,False,True,False,False,False,True,True,NaN,False,24.0,True,Japanese,True,False,False,False,True
14820,LrkKYQE4GFbrLljB1e-1uQ,7CSdKgXpErpxNDlcxRNmyw,2xxkaRy7rP5EUyjFt2J5kA,5,2021-12-31 02:09:13,Nikka Ramen,Goleta,4.5,562,True,True,True,False,True,True,True,True,True,True,False,True,True,False,False,True,False,False,False,True,True,NaN,False,24.0,True,Japanese,True,False,False,False,True
14821,ANLkn3qlUFauQx2QvYCpOA,GHtcfd7DYF_awESn6jCBtQ,2xxkaRy7rP5EUyjFt2J5kA,5,2020-10-11 22:16:48,Nikka Ramen,Goleta,4.5,562,True,True,True,False,True,True,True,True,True,True,False,True,True,False,False,True,False,False,False,True,True,NaN,False,24.0,True,Japanese,True,False,False,False,True
14822,faZzKA1okAUGVDh-AC4X4w,n6fiQSlPZiRojE55MS77yg,2xxkaRy7rP5EUyjFt2J5kA,3,2021-12-13 03:19:20,Nikka Ramen,Goleta,4.5,562,True,True,True,False,True,True,True,True,True,True,False,True,True,False,False,True,False,False,False,True,True,NaN,False,24.0,True,Japanese,True,False,False,False,True
14823,Thf0D-SqPeXcn3faH7rM3Q,y783d3C4Yjm_cGqHvPQnmA,2xxkaRy7rP5EUyjFt2J5kA,4,2017-03-12 06:45:25,Nikka Ramen,Goleta,4.5,562,True,True,True,False,True,True,True,True,True,True,False,True,True,False,False,True,False,False,False,True,True,NaN,False,24.0,True,Japanese,True,False,False,False,True

       comment_star  average_stars  review_count    Total_hour
count  14824.000000   14824.000000  14824.000000  14824.000000
mean       3.875405       3.849231    411.831894     45.926875
std        1.397584       0.533916    288.900753     21.489717
min        1.000000       2.500000      5.000000      0.000000
25%        3.000000       3.500000    200.000000     26.000000
50%        4.000000       4.000000    328.000000     44.000000
75%        5.000000       4.500000    488.000000     62.000000
max        5.000000       4.500000    983.000000    102.000000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14824 entries, 0 to 14823
Data columns (total 40 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   review_id                   14824 non-null  object
 1   user_id                     14824 non-null  object
 2   business_id                 14824 non-null  object
 3   comment_star                14824 non-null  int64
 4   date                        14824 non-null  object
 5   name                        14824 non-null  object
 6   city                        14824 non-null  object
 7   average_stars               14824 non-null  float64
 8   review_count                14824 non-null  int64
 9   BusinessAcceptsCreditCards  14824 non-null  bool
 10  BikeParking                 14824 non-null  bool
 11  RestaurantsTakeOut          13215 non-null  object
 12  RestaurantsReservations     14685 non-null  object
 13  RestaurantsTableService     11745 non-null  object
 14  GoodForKids                 13258 non-null  object
 15  WheelchairAccessible        8464 non-null   object
 16  RestaurantsDelivery         11383 non-null  object
 17  HasTV                       14699 non-null  object
 18  Alcohol                     14808 non-null  object
 19  DogsAllowed                 11081 non-null  object
 20  RestaurantsGoodForGroups    14241 non-null  object
 21  WiFi                        14689 non-null  object
 22  garage                      14524 non-null  object
 23  street                      14457 non-null  object
 24  lot                         14591 non-null  object
 25  valet                       14808 non-null  object
 26  dessert                     12885 non-null  object
 27  latenight                   12849 non-null  object
 28  lunch                       13102 non-null  object
 29  dinner                      14163 non-null  object
 30  brunch                      11716 non-null  object
 31  breakfast                   13645 non-null  object
 32  Total_hour                  14824 non-null  float64
 33  acceptable_noise            14043 non-null  object
 34  general_category            14824 non-null  object
 35  hipster_trendy              12813 non-null  object
 36  upscale_classy              14280 non-null  object
 37  divey_env                   11809 non-null  object
 38  intimate_env                12368 non-null  object
 39  casual_env                  13733 non-null  object
dtypes: bool(2), float64(2), int64(2), object(34)
memory usage: 4.3+ MB

In [27]:
null_df = pd.DataFrame(data_train.isnull().sum())
print(data_train.isnull().sum())

review_id                        0
user_id                          0
business_id                      0
comment_star                     0
date                             0
name                             0
city                             0
average_stars                    0
review_count                     0
BusinessAcceptsCreditCards       0
BikeParking                      0
RestaurantsTakeOut            1609
RestaurantsReservations        139
RestaurantsTableService       3079
GoodForKids                   1566
WheelchairAccessible          6360
RestaurantsDelivery           3441
HasTV                          125
Alcohol                         16
DogsAllowed                   3743
RestaurantsGoodForGroups       583
WiFi                           135
garage                         300
street                         367
lot                            233
valet                           16
dessert                       1939
latenight                     1975
lunch                         1722
dinner                         661
brunch                        3108
breakfast                     1179
Total_hour                       0
acceptable_noise               781
general_category                 0
hipster_trendy                2011
upscale_classy                 544
divey_env                     3015
intimate_env                  2456
casual_env                    1091
dtype: int64

In [28]:
print(list(null_df.columns))
print(list(null_df.index))

[0]
['review_id', 'user_id', 'business_id', 'comment_star', 'date', 'name', 'city', 'average_stars', 'review_count', 'BusinessAcceptsCreditCards', 'BikeParking', 'RestaurantsTakeOut', 'RestaurantsReservations', 'RestaurantsTableService', 'GoodForKids', 'WheelchairAccessible', 'RestaurantsDelivery', 'HasTV', 'Alcohol', 'DogsAllowed', 'RestaurantsGoodForGroups', 'WiFi', 'garage', 'street', 'lot', 'valet', 'dessert', 'latenight', 'lunch', 'dinner', 'brunch', 'breakfast', 'Total_hour', 'acceptable_noise', 'general_category', 'hipster_trendy', 'upscale_classy', 'divey_env', 'intimate_env', 'casual_env']

In [29]:
null_df.columns = ['null_num']
new = null_df[null_df['null_num'] > 1000]
gt_1000_var = list(new.index)
gt_1000_var
#target_var = less_1000_var[8:]

['RestaurantsTakeOut',
 'RestaurantsTableService',
 'GoodForKids',
 'WheelchairAccessible',
 'RestaurantsDelivery',
 'DogsAllowed',
 'dessert',
 'latenight',
 'lunch',
 'brunch',
 'breakfast',
 'hipster_trendy',
 'divey_env',
 'intimate_env',
 'casual_env']

In [30]:
data_train

,review_id,user_id,business_id,comment_star,date,name,city,average_stars,review_count,BusinessAcceptsCreditCards,BikeParking,RestaurantsTakeOut,RestaurantsReservations,RestaurantsTableService,GoodForKids,WheelchairAccessible,RestaurantsDelivery,HasTV,Alcohol,DogsAllowed,RestaurantsGoodForGroups,WiFi,garage,street,lot,valet,dessert,latenight,lunch,dinner,brunch,breakfast,Total_hour,acceptable_noise,general_category,hipster_trendy,upscale_classy,divey_env,intimate_env,casual_env
0,cSsTxwkhjUTOUkLt7Y4LAA,_QrXKSZm2D6iPQqwChxsiw,MiMRlsXOpHJMSTDAuw8s1w,4,2020-02-07 00:29:55,Suâs Bowl,Isla Vista,3.5,18,True,True,True,False,False,NaN,NaN,True,True,False,False,NaN,True,True,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,44.0,NaN,Asian Fusion,NaN,NaN,NaN,NaN,NaN
1,vz9y6qxlZkttwprvVEbWmw,2PeqtdiehYm82TXymQUGow,MiMRlsXOpHJMSTDAuw8s1w,4,2020-07-23 03:31:41,Suâs Bowl,Isla Vista,3.5,18,True,True,True,False,False,NaN,NaN,True,True,False,False,NaN,True,True,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,44.0,NaN,Asian Fusion,NaN,NaN,NaN,NaN,NaN
2,A27fyLXY_wsoEi61uZR8qQ,En60uoM-AoTtQ9-nZco92A,MiMRlsXOpHJMSTDAuw8s1w,3,2020-03-23 01:03:20,Suâs Bowl,Isla Vista,3.5,18,True,True,True,False,False,NaN,NaN,True,True,False,False,NaN,True,True,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,44.0,NaN,Asian Fusion,NaN,NaN,NaN,NaN,NaN
3,_FhgxOElUpqgVu6NYQ_bkg,LcBZt_bpU5CqwtDJwB3OCg,MiMRlsXOpHJMSTDAuw8s1w,4,2019-12-09 01:15:53,Suâs Bowl,Isla Vista,3.5,18,True,True,True,False,False,NaN,NaN,True,True,False,False,NaN,True,True,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,44.0,NaN,Asian Fusion,NaN,NaN,NaN,NaN,NaN
4,9yKOHgmubnxyIzoWRKad7w,FxdCb7Dl8c2hYn2t_7qRBA,MiMRlsXOpHJMSTDAuw8s1w,5,2020-12-12 03:17:49,Suâs Bowl,Isla Vista,3.5,18,True,True,True,False,False,NaN,NaN,True,True,False,False,NaN,True,True,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,44.0,NaN,Asian Fusion,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14819,DtTPlU8KX5q_AJxYh_ctuA,RLW98dloIcfl57JPK5rMXQ,2xxkaRy7rP5EUyjFt2J5kA,5,2020-05-01 00:00:29,Nikka Ramen,Goleta,4.5,562,True,True,True,False,True,True,True,True,True,True,False,True,True,False,False,True,False,False,False,True,True,NaN,False,24.0,True,Japanese,True,False,False,False,True
14820,LrkKYQE4GFbrLljB1e-1uQ,7CSdKgXpErpxNDlcxRNmyw,2xxkaRy7rP5EUyjFt2J5kA,5,2021-12-31 02:09:13,Nikka Ramen,Goleta,4.5,562,True,True,True,False,True,True,True,True,True,True,False,True,True,False,False,True,False,False,False,True,True,NaN,False,24.0,True,Japanese,True,False,False,False,True
14821,ANLkn3qlUFauQx2QvYCpOA,GHtcfd7DYF_awESn6jCBtQ,2xxkaRy7rP5EUyjFt2J5kA,5,2020-10-11 22:16:48,Nikka Ramen,Goleta,4.5,562,True,True,True,False,True,True,True,True,True,True,False,True,True,False,False,True,False,False,False,True,True,NaN,False,24.0,True,Japanese,True,False,False,False,True
14822,faZzKA1okAUGVDh-AC4X4w,n6fiQSlPZiRojE55MS77yg,2xxkaRy7rP5EUyjFt2J5kA,3,2021-12-13 03:19:20,Nikka Ramen,Goleta,4.5,562,True,True,True,False,True,True,True,True,True,True,False,True,True,False,False,True,False,False,False,True,True,NaN,False,24.0,True,Japanese,True,False,False,False,True
14823,Thf0D-SqPeXcn3faH7rM3Q,y783d3C4Yjm_cGqHvPQnmA,2xxkaRy7rP5EUyjFt2J5kA,4,2017-03-12 06:45:25,Nikka Ramen,Goleta,4.5,562,True,True,True,False,True,True,True,True,True,True,False,True,True,False,False,True,False,False,False,True,True,NaN,False,24.0,True,Japanese,True,False,False,False,True

In [31]:
data_train

,review_id,user_id,business_id,comment_star,date,name,city,average_stars,review_count,BusinessAcceptsCreditCards,BikeParking,RestaurantsTakeOut,RestaurantsReservations,RestaurantsTableService,GoodForKids,WheelchairAccessible,RestaurantsDelivery,HasTV,Alcohol,DogsAllowed,RestaurantsGoodForGroups,WiFi,garage,street,lot,valet,dessert,latenight,lunch,dinner,brunch,breakfast,Total_hour,acceptable_noise,general_category,hipster_trendy,upscale_classy,divey_env,intimate_env,casual_env
0,cSsTxwkhjUTOUkLt7Y4LAA,_QrXKSZm2D6iPQqwChxsiw,MiMRlsXOpHJMSTDAuw8s1w,4,2020-02-07 00:29:55,Suâs Bowl,Isla Vista,3.5,18,True,True,True,False,False,NaN,NaN,True,True,False,False,NaN,True,True,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,44.0,NaN,Asian Fusion,NaN,NaN,NaN,NaN,NaN
1,vz9y6qxlZkttwprvVEbWmw,2PeqtdiehYm82TXymQUGow,MiMRlsXOpHJMSTDAuw8s1w,4,2020-07-23 03:31:41,Suâs Bowl,Isla Vista,3.5,18,True,True,True,False,False,NaN,NaN,True,True,False,False,NaN,True,True,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,44.0,NaN,Asian Fusion,NaN,NaN,NaN,NaN,NaN
2,A27fyLXY_wsoEi61uZR8qQ,En60uoM-AoTtQ9-nZco92A,MiMRlsXOpHJMSTDAuw8s1w,3,2020-03-23 01:03:20,Suâs Bowl,Isla Vista,3.5,18,True,True,True,False,False,NaN,NaN,True,True,False,False,NaN,True,True,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,44.0,NaN,Asian Fusion,NaN,NaN,NaN,NaN,NaN
3,_FhgxOElUpqgVu6NYQ_bkg,LcBZt_bpU5CqwtDJwB3OCg,MiMRlsXOpHJMSTDAuw8s1w,4,2019-12-09 01:15:53,Suâs Bowl,Isla Vista,3.5,18,True,True,True,False,False,NaN,NaN,True,True,False,False,NaN,True,True,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,44.0,NaN,Asian Fusion,NaN,NaN,NaN,NaN,NaN
4,9yKOHgmubnxyIzoWRKad7w,FxdCb7Dl8c2hYn2t_7qRBA,MiMRlsXOpHJMSTDAuw8s1w,5,2020-12-12 03:17:49,Suâs Bowl,Isla Vista,3.5,18,True,True,True,False,False,NaN,NaN,True,True,False,False,NaN,True,True,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,44.0,NaN,Asian Fusion,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14819,DtTPlU8KX5q_AJxYh_ctuA,RLW98dloIcfl57JPK5rMXQ,2xxkaRy7rP5EUyjFt2J5kA,5,2020-05-01 00:00:29,Nikka Ramen,Goleta,4.5,562,True,True,True,False,True,True,True,True,True,True,False,True,True,False,False,True,False,False,False,True,True,NaN,False,24.0,True,Japanese,True,False,False,False,True
14820,LrkKYQE4GFbrLljB1e-1uQ,7CSdKgXpErpxNDlcxRNmyw,2xxkaRy7rP5EUyjFt2J5kA,5,2021-12-31 02:09:13,Nikka Ramen,Goleta,4.5,562,True,True,True,False,True,True,True,True,True,True,False,True,True,False,False,True,False,False,False,True,True,NaN,False,24.0,True,Japanese,True,False,False,False,True
14821,ANLkn3qlUFauQx2QvYCpOA,GHtcfd7DYF_awESn6jCBtQ,2xxkaRy7rP5EUyjFt2J5kA,5,2020-10-11 22:16:48,Nikka Ramen,Goleta,4.5,562,True,True,True,False,True,True,True,True,True,True,False,True,True,False,False,True,False,False,False,True,True,NaN,False,24.0,True,Japanese,True,False,False,False,True
14822,faZzKA1okAUGVDh-AC4X4w,n6fiQSlPZiRojE55MS77yg,2xxkaRy7rP5EUyjFt2J5kA,3,2021-12-13 03:19:20,Nikka Ramen,Goleta,4.5,562,True,True,True,False,True,True,True,True,True,True,False,True,True,False,False,True,False,False,False,True,True,NaN,False,24.0,True,Japanese,True,False,False,False,True
14823,Thf0D-SqPeXcn3faH7rM3Q,y783d3C4Yjm_cGqHvPQnmA,2xxkaRy7rP5EUyjFt2J5kA,4,2017-03-12 06:45:25,Nikka Ramen,Goleta,4.5,562,True,True,True,False,True,True,True,True,True,True,False,True,True,False,False,True,False,False,False,True,True,NaN,False,24.0,True,Japanese,True,False,False,False,True

In [32]:
for i in gt_1000_var:
    data_train.drop( i, axis = 1, inplace = True)
other_no_need = ["review_id", "user_id","date", "name", "city","general_category"]
for k in other_no_need:
    data_train.drop(k ,axis = 1,inplace = True)

In [33]:
copy_df = data_train.copy( deep = True )

In [34]:
non_na  = copy_df.dropna(axis = 0, how = 'any', thresh=None, subset=None, inplace=False)

In [35]:
non_na.isnull().head()

,business_id,comment_star,average_stars,review_count,BusinessAcceptsCreditCards,BikeParking,RestaurantsReservations,HasTV,Alcohol,RestaurantsGoodForGroups,WiFi,garage,street,lot,valet,dinner,Total_hour,acceptable_noise,upscale_classy
26,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [36]:
new_data = non_na.reset_index()
new_data = new_data.drop('index', axis = 1)
new_data

,business_id,comment_star,average_stars,review_count,BusinessAcceptsCreditCards,BikeParking,RestaurantsReservations,HasTV,Alcohol,RestaurantsGoodForGroups,WiFi,garage,street,lot,valet,dinner,Total_hour,acceptable_noise,upscale_classy
0,vC2qm1y3Au5czBtbhc-DNw,4,3.0,167,True,True,True,True,True,True,False,False,True,True,False,True,35.0,True,False
1,vC2qm1y3Au5czBtbhc-DNw,4,3.0,167,True,True,True,True,True,True,False,False,True,True,False,True,35.0,True,False
2,vC2qm1y3Au5czBtbhc-DNw,4,3.0,167,True,True,True,True,True,True,False,False,True,True,False,True,35.0,True,False
3,vC2qm1y3Au5czBtbhc-DNw,5,3.0,167,True,True,True,True,True,True,False,False,True,True,False,True,35.0,True,False
4,vC2qm1y3Au5czBtbhc-DNw,5,3.0,167,True,True,True,True,True,True,False,False,True,True,False,True,35.0,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13373,2xxkaRy7rP5EUyjFt2J5kA,5,4.5,562,True,True,False,True,True,True,True,False,False,True,False,True,24.0,True,False
13374,2xxkaRy7rP5EUyjFt2J5kA,5,4.5,562,True,True,False,True,True,True,True,False,False,True,False,True,24.0,True,False
13375,2xxkaRy7rP5EUyjFt2J5kA,5,4.5,562,True,True,False,True,True,True,True,False,False,True,False,True,24.0,True,False
13376,2xxkaRy7rP5EUyjFt2J5kA,3,4.5,562,True,True,False,True,True,True,True,False,False,True,False,True,24.0,True,False
13377,2xxkaRy7rP5EUyjFt2J5kA,4,4.5,562,True,True,False,True,True,True,True,False,False,True,False,True,24.0,True,False

In [37]:
for u in new_data.columns:
    print(u)
    if u == "business_id":
        continue
    #print(new_data[u])
    if new_data[u].dtype==object or new_data[u].dtype==bool:
        new_data[u]=new_data[u].astype('int')

business_id
comment_star
average_stars
review_count
BusinessAcceptsCreditCards
BikeParking
RestaurantsReservations
HasTV
Alcohol
RestaurantsGoodForGroups
WiFi
garage
street
lot
valet
dinner
Total_hour
acceptable_noise
upscale_classy

In [38]:
new_data["comment_star"].apply(str)

0        4
1        4
2        4
3        5
4        5
        ..
13373    5
13374    5
13375    5
13376    3
13377    4
Name: comment_star, Length: 13378, dtype: object

In [39]:
new_data.head()

,business_id,comment_star,average_stars,review_count,BusinessAcceptsCreditCards,BikeParking,RestaurantsReservations,HasTV,Alcohol,RestaurantsGoodForGroups,WiFi,garage,street,lot,valet,dinner,Total_hour,acceptable_noise,upscale_classy
0,vC2qm1y3Au5czBtbhc-DNw,4,3.0,167,1,1,1,1,1,1,0,0,1,1,0,1,35.0,1,0
1,vC2qm1y3Au5czBtbhc-DNw,4,3.0,167,1,1,1,1,1,1,0,0,1,1,0,1,35.0,1,0
2,vC2qm1y3Au5czBtbhc-DNw,4,3.0,167,1,1,1,1,1,1,0,0,1,1,0,1,35.0,1,0
3,vC2qm1y3Au5czBtbhc-DNw,5,3.0,167,1,1,1,1,1,1,0,0,1,1,0,1,35.0,1,0
4,vC2qm1y3Au5czBtbhc-DNw,5,3.0,167,1,1,1,1,1,1,0,0,1,1,0,1,35.0,1,0

In [40]:
outputpath

'C:\\Users\\86188\\Desktop\\628\\module 3\\new.csv'

In [41]:
import os
outputpath = os.getcwd()
outputpath = os.path.join(outputpath, "final_data.csv")
new_data.to_csv(outputpath,sep = ',', index = False, header = True)